// Place any global data in this file.
// You can import this data from anywhere in your site by using the `import` keyword.

export const URL_SITE = "https://fmarcos.dev";
// export const URL_SITE = "http://localhost:4321/";
export const SITE_TITLE = "fmarcos";
export const SITE_DESCRIPTION = "website";
export const HOME_PAGE = "/about_me";
export const SOCIAL_PAGE = "/social";
export const BLOG_PAGE = "/blog";
export const PROJECTS_PAGE = "/projects";
export const uNFixeD = "Freddy Huaylla";
export const PROFESSION = "ANALISTA PROGRAMADOR";
export const WELCOME_MESSAGES = [
  "¿Sabías que JavaScript fue creado en solo 10 días?",
  "Dato curioso: JavaScript no tiene nada que ver con Java.",
  "En JavaScript, '[] + []' da como resultado una cadena vacía.",
  "JavaScript inicialmente se llamó Mocha.",
  "En JavaScript, 'NaN' significa 'Not-a-Number'.",
  "JavaScript es un lenguaje interpretado, no compilado.",
  "Las funciones en JavaScript son de primera clase.",
  "JavaScript puede funcionar tanto en el cliente como en el servidor.",
  "El primer navegador en soportar JavaScript fue Netscape.",
  "JavaScript no tiene tipos de datos enteros.",
  "En JavaScript, 'undefined' y 'null' son diferentes.",
  "JavaScript soporta programación orientada a objetos, funcional y basada en prototipos.",
  "El operador '===' en JavaScript también compara tipos de datos.",
  "JavaScript tiene solo un tipo de número: el número de 64 bits IEEE 754.",
  "En JavaScript, '0.1 + 0.2' no es exactamente igual a '0.3'.",
  "JavaScript permite funciones anidadas.",
  "Los arrays en JavaScript son objetos.",
  "JavaScript es un lenguaje débilmente tipado.",
  "El 'use strict' en JavaScript activa el modo estricto.",
  "JavaScript tiene closures o cierres.",
  "JSON significa JavaScript Object Notation.",
  "JavaScript tiene funciones de orden superior.",
  "Las promesas en JavaScript se usan para operaciones asíncronas.",
  "JavaScript es compatible con ECMAScript.",
  "El 'this' en JavaScript depende de cómo se llama a la función.",
  "JavaScript tiene un solo hilo de ejecución.",
  "Los módulos en JavaScript permiten dividir el código en archivos separados.",
  "JavaScript tiene métodos de array como 'map', 'filter' y 'reduce'.",
  "El 'async/await' simplifica el manejo de promesas.",
  "En JavaScript, 'typeof null' devuelve 'object'.",
  "JavaScript permite la desestructuración de arrays y objetos.",
  "Los generadores en JavaScript permiten funciones pausables.",
  "JavaScript tiene el objeto global 'window' en el navegador.",
  "El 'event loop' en JavaScript maneja la concurrencia.",
  "JavaScript permite el uso de funciones flecha (arrow functions).",
  "El 'spread operator' en JavaScript se usa para expandir elementos.",
  "JavaScript tiene 'Set' y 'Map' para colecciones de datos.",
  "El DOM (Document Object Model) se manipula con JavaScript.",
  "En JavaScript, '== null' verifica tanto 'null' como 'undefined'.",
  "JavaScript tiene 'Proxy' para interceptar operaciones en objetos.",
  "JavaScript puede detectar el tipo de dispositivo con 'navigator.userAgent'.",
  "El 'Temporal Dead Zone' ocurre con variables 'let' y 'const'.",
  "JavaScript tiene 'WeakMap' y 'WeakSet' para referencias débiles.",
  "El operador '??' en JavaScript es el nullish coalescing.",
  "Las etiquetas de plantillas (template literals) permiten interpolación de cadenas.",
  "JavaScript tiene módulos nativos desde ES6.",
  "El 'fetch API' en JavaScript facilita las peticiones HTTP.",
  "JavaScript permite herencia prototípica.",
  "Los 'event listeners' en JavaScript manejan eventos de usuario.",
  "En JavaScript, los números grandes se representan con 'BigInt'.",
  "JavaScript tiene 'Intl' para internacionalización.",
  "El operador '?.' en JavaScript es el optional chaining.",
  "JavaScript soporta la programación funcional.",
  "El 'new' en JavaScript crea una instancia de un objeto.",
  "JavaScript tiene 'Symbol' para crear identificadores únicos.",
  "En JavaScript, los arrays pueden ser sparse.",
  "Los 'descriptores de propiedades' en JavaScript definen características de propiedades.",
  "JavaScript permite crear objetos con 'Object.create'.",
  "El 'debouncing' en JavaScript mejora el rendimiento de eventos.",
  "Los 'iterables' en JavaScript permiten la iteración de colecciones.",
  "JavaScript tiene 'async iterators' para iteraciones asíncronas.",
  "El 'Reflect' API en JavaScript facilita la manipulación de objetos.",
  "JavaScript puede manipular el DOM con 'document.querySelector'.",
  "El 'service worker' en JavaScript permite aplicaciones web offline.",
  "JavaScript permite programar con 'decorators'.",
  "Los 'tagged templates' en JavaScript manipulan cadenas de plantillas.",
  "JavaScript tiene el 'URL API' para manipular URLs.",
  "En JavaScript, 'Promise.all' maneja múltiples promesas.",
  "JavaScript permite crear 'custom elements' para Web Components.",
  "El 'requestAnimationFrame' en JavaScript optimiza animaciones.",
  "JavaScript tiene el 'AbortController' para cancelar fetch requests.",
  "El 'Function.prototype.apply' en JavaScript invoca funciones con arrays.",
  "JavaScript permite la 'memoización' para mejorar el rendimiento.",
  "Los 'data attributes' en HTML se pueden acceder con JavaScript.",
  "JavaScript puede manipular estilos CSS con 'element.style'.",
  "El 'pointer events' en JavaScript maneja entradas de punteros.",
  "JavaScript permite la comunicación entre iframes con 'postMessage'.",
  "El 'document.readyState' en JavaScript indica el estado de carga del documento.",
  "JavaScript puede crear gráficos interactivos con 'Canvas API'.",
  "El 'WebAssembly' en JavaScript ejecuta código binario en el navegador.",
  "JavaScript permite la autenticación con 'OAuth'.",
  "El 'navigator.geolocation' en JavaScript accede a la ubicación del usuario.",
  "JavaScript tiene 'event bubbling' y 'event capturing'.",
  "El 'SharedArrayBuffer' en JavaScript permite la memoria compartida entre hilos.",
  "JavaScript puede interactuar con hardware mediante 'WebUSB API'.",
  "El 'localStorage' en JavaScript almacena datos localmente.",
  "JavaScript permite la ejecución de tareas en segundo plano con 'Web Workers'.",
  "El 'WebRTC' en JavaScript habilita la comunicación en tiempo real.",
  "JavaScript soporta la edición de documentos con 'contentEditable'.",
  "El 'MutationObserver' en JavaScript observa cambios en el DOM.",
  "JavaScript tiene 'generator functions' que pueden pausar y reanudar su ejecución.",
  "El 'IntersectionObserver' en JavaScript detecta la visibilidad de elementos.",
  "JavaScript puede interactuar con el sistema de archivos usando 'File API'.",
  "El 'EventSource' en JavaScript maneja eventos de servidor.",
  "JavaScript soporta la 'asincronía' con 'callbacks', 'promises' y 'async/await'.",
  "El 'template' tag en HTML permite crear contenido reutilizable con JavaScript.",
  "JavaScript puede acceder a la cámara y micrófono con 'getUserMedia'.",
];
