name: Create and push tags

on:
  push:
    branches:
      - main # Se activa al hacer push a la rama principal

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create and push tag
        run: |
          TAG="v1.0.0-$(git rev-parse --short HEAD)"  # Crear el tag usando el hash del commit
          git tag $TAG  # Crear el tag
          git push origin $TAG  # Hacer push del tag
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_TOKEN }} # Token para autenticación
