name: Create and Push Tag

on:
  push:
    branches:
      - main # Este workflow se activará cuando haya un push a la rama principal

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Hacer checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar Git
      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Paso 3: Crear el tag y hacer push
      - name: Create and push tag
        run: |
          TAG="v1.0.0-$(git rev-parse --short HEAD)"
          git tag $TAG
          git push origin $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub Actions usará este token automáticamente

#
# name: Create and Push Tag

# on:
#   push:
#     branches:
#       - main # Este workflow se activará cuando haya un push a la rama principal

# jobs:
#   create_tag:
#     runs-on: ubuntu-latest

#     steps:
#       # Paso 1: Hacer checkout del repositorio
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       # Paso 2: Configurar Git para usar el bot de GitHub Actions
#       - name: Set up Git user
#         run: |
#           git config user.name "github-actions[bot]"
#           git config user.email "github-actions[bot]@users.noreply.github.com"

#       # Paso 3: Crear y hacer push del tag
#       - name: Create a new tag based on the commit hash
#         run: |
#           TAG="v1.0.0-$(git rev-parse --short HEAD)"  # Crear el tag usando el hash del commit
#           echo "Creating tag $TAG"
#           git tag $TAG  # Crear el tag localmente

#       # Paso 4: Configurar autenticación con el token
#       - name: Set up authentication for push
#         run: |
#           git remote set-url origin https://${{ secrets.PERMISSION_CREATED_FOR_GHACTIONS }}@github.com/${{ github.repository }}.git

#       # Paso 5: Hacer push del tag al repositorio remoto
#       - name: Push tag to remote
#         run: |
#           git push origin $TAG  # Hacer push del tag al repositorio remoto

# name: Create and Push Tag

# on:
#   push:
#     branches:
#       - main # Este workflow se activará cuando haya un push a la rama principal

# jobs:
#   create_tag:
#     runs-on: ubuntu-latest

#     steps:
#       # Paso 1: Hacer checkout del repositorio
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       # Paso 2: Configurar Git para usar el bot de GitHub Actions
#       - name: Set up Git user
#         run: |
#           git config user.name "github-actions[bot]"
#           git config user.email "github-actions[bot]@users.noreply.github.com"

#       # Paso 3: Crear y hacer push del tag
#       - name: Create a new tag based on the commit hash
#         run: |
#           TAG="v1.0.0-$(git rev-parse --short HEAD)"  # Crear el tag usando el hash del commit
#           echo "Creating tag $TAG"
#           git tag $TAG  # Crear el tag localmente

#       # Paso 4: Usar GITHUB_TOKEN para autenticación
#       - name: Set up authentication with GITHUB_TOKEN
#         run: |
#           git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

#       # Paso 5: Hacer push del tag al repositorio remoto
#       - name: Push tag to remote
#         run: |
#           git push origin $TAG  # Hacer push del tag al repositorio remoto
