name: Test GitHub Actions with Token

on:
  push:
    branches:
      - main # Este workflow se activará cuando haya un push a la rama principal

jobs:
  test_action:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Hacer checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Configurar Git para usar el bot de GitHub Actions
      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Paso 3: Crear un nuevo tag basado en el commit hash
      - name: Create a new tag based on the commit hash
        run: |
          TAG="v1.0.0-$(git rev-parse --short HEAD)"  # Crear el tag usando el hash del commit
          echo "Creating tag $TAG"
          git tag $TAG  # Crear el tag localmente

      # Paso 4: Configurar autenticación para el push
      - name: Set up Git authentication
        run: |
          git remote set-url origin https://$GITHUB_ACTOR:${{ secrets.PERMISSION_CREATED_FOR_GHACTIONS }}@github.com/$GITHUB_REPOSITORY.git

      # Paso 5: Hacer push del tag al repositorio remoto
      - name: Push tag to remote
        run: |
          git push origin $TAG  # Hacer push del tag al repositorio remoto
