name: Create and Push Tag

on:
  # Puedes ejecutarlo manualmente desde la interfaz de GitHub
  workflow_dispatch:
    inputs:
      tag_version:
        description: "Versión del tag (ejemplo: v1.0.0)"
        required: true
      tag_message:
        description: "Mensaje para el tag"
        required: true
        default: "Nueva versión"

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Necesitamos tener acceso completo al historial para crear tags
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create and Push Tag
        run: |
          # Crear un tag anotado con el mensaje proporcionado
          git tag -a ${{ github.event.inputs.tag_version }} -m "${{ github.event.inputs.tag_message }}"

          # Push del tag al repositorio
          git push origin ${{ github.event.inputs.tag_version }}
        env:
          # Usar el token de GitHub para autenticación
          # Intentará usar GITHUB_TOKEN primero, si no existe usará tu token personalizado
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || secrets.PERMISSION_CREATED_FOR_GHACTIONS }}
